---
- name: Update and upgrade packages on selected hosts with optimizations
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update package cache and upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
      register: upgrade_result
      tags: [update, upgrade]

    - name: Clean up unnecessary packages and cache
      ansible.builtin.apt:
        autoremove: true
        autoclean: true
      tags: cleanup

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      tags: check

    - name: Display packages that were upgraded
      ansible.builtin.debug:
        var: upgrade_result.stdout_lines
      when: upgrade_result.changed
      tags: info

    - name: Reboot system if required
      ansible.builtin.reboot:
        msg: 'Reboot initiated by Ansible for package updates'
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
      tags: reboot

    - name: Verify system is responsive after reboot
      ansible.builtin.ping:
      when: reboot_required_file.stat.exists
      tags: verify
